-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2017-04-03 22:45:25 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012




CREATE
  TABLE Body
  (
    Poradi     INTEGER NOT NULL ,
    Pocet_bodu INTEGER NOT NULL
  )
  ON "default"
GO
ALTER TABLE Body ADD CONSTRAINT Body_PK PRIMARY KEY CLUSTERED (Poradi)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE GP
  (
    ID    INTEGER NOT NULL ,
    Nazev VARCHAR (50) NOT NULL ,
    Datum DATE ,
    Delka_okruhu FLOAT NOT NULL ,
    Pocet_kol   INTEGER ,
    Staty_ID    INTEGER NOT NULL ,
    Uzivatel_ID INTEGER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
GP__IDX ON GP
(
  Uzivatel_ID
)
ON "default"
GO
ALTER TABLE GP ADD CONSTRAINT GP_PK PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Jezdci
  (
    ID                   INTEGER NOT NULL ,
    Jmeno                VARCHAR (30) NOT NULL ,
    Prijmeni             VARCHAR (40) NOT NULL ,
    Startovni_cislo      INTEGER ,
    Datum_narozeni       DATE NOT NULL ,
    Tymy_ID              INTEGER NOT NULL ,
    Staty_ID             INTEGER NOT NULL ,
    Motory_Seriove_cislo INTEGER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Jezdci__IDX ON Jezdci
(
  Motory_Seriove_cislo
)
ON "default"
GO
ALTER TABLE Jezdci ADD CONSTRAINT Jezdci_PK PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Motory
  (
    Seriove_cislo INTEGER NOT NULL ,
    Pocet_pouziti INTEGER NOT NULL
  )
  ON "default"
GO
ALTER TABLE Motory ADD CONSTRAINT Motory_PK PRIMARY KEY CLUSTERED (
Seriove_cislo)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Staty
  (
    ID        INTEGER NOT NULL ,
    Nazev     VARCHAR (40) NOT NULL ,
    Narodnost VARCHAR (40) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Staty ADD CONSTRAINT Staty_PK PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Tymy
  (
    ID                  INTEGER NOT NULL ,
    Nazev               VARCHAR (40) NOT NULL ,
    Dodavatel_pneumatik VARCHAR (20) NOT NULL ,
    Vyrobce_motoru_ID   INTEGER NOT NULL ,
    Staty_ID            INTEGER NOT NULL ,
    Uzivatel_ID         INTEGER NOT NULL
  )
  ON "default"
GO
CREATE UNIQUE NONCLUSTERED INDEX
Tymy__IDX ON Tymy
(
  Uzivatel_ID
)
ON "default"
GO
ALTER TABLE Tymy ADD CONSTRAINT Tymy_PK PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Uzivatel
  (
    ID    INTEGER NOT NULL ,
    Login VARCHAR (40) NOT NULL ,
    Heslo VARCHAR (60) NOT NULL ,
    Type  VARCHAR (5) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Uzivatel ADD CONSTRAINT Uzivatel_PK PRIMARY KEY CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Vyrobce_motoru
  (
    ID    INTEGER NOT NULL ,
    Nazev VARCHAR (30) NOT NULL
  )
  ON "default"
GO
ALTER TABLE Vyrobce_motoru ADD CONSTRAINT Vyrobce_motoru_PK PRIMARY KEY
CLUSTERED (ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

CREATE
  TABLE Vysledky
  (
    GP_ID       INTEGER NOT NULL ,
    Body_Poradi INTEGER NOT NULL ,
    Jezdci_ID   INTEGER NOT NULL
  )
  ON "default"
GO
ALTER TABLE Vysledky ADD CONSTRAINT Vysledky_PK PRIMARY KEY CLUSTERED (GP_ID,
Body_Poradi, Jezdci_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO

ALTER TABLE GP
ADD CONSTRAINT GP_Staty_FK FOREIGN KEY
(
Staty_ID
)
REFERENCES Staty
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE GP
ADD CONSTRAINT GP_Uzivatel_FK FOREIGN KEY
(
Uzivatel_ID
)
REFERENCES Uzivatel
(
ID
)
ON
DELETE CASCADE ON
UPDATE NO ACTION
GO

ALTER TABLE Jezdci
ADD CONSTRAINT Jezdci_Motory_FK FOREIGN KEY
(
Motory_Seriove_cislo
)
REFERENCES Motory
(
Seriove_cislo
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Jezdci
ADD CONSTRAINT Jezdci_Staty_FK FOREIGN KEY
(
Staty_ID
)
REFERENCES Staty
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Jezdci
ADD CONSTRAINT Jezdci_Tymy_FK FOREIGN KEY
(
Tymy_ID
)
REFERENCES Tymy
(
ID
)
ON
DELETE CASCADE ON
UPDATE NO ACTION
GO

ALTER TABLE Tymy
ADD CONSTRAINT Tymy_Staty_FK FOREIGN KEY
(
Staty_ID
)
REFERENCES Staty
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Tymy
ADD CONSTRAINT Tymy_Uzivatel_FK FOREIGN KEY
(
Uzivatel_ID
)
REFERENCES Uzivatel
(
ID
)
ON
DELETE CASCADE ON
UPDATE NO ACTION
GO

ALTER TABLE Tymy
ADD CONSTRAINT Tymy_Vyrobce_motoru_FK FOREIGN KEY
(
Vyrobce_motoru_ID
)
REFERENCES Vyrobce_motoru
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Vysledky
ADD CONSTRAINT Vysledky_Body_FK FOREIGN KEY
(
Body_Poradi
)
REFERENCES Body
(
Poradi
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Vysledky
ADD CONSTRAINT Vysledky_GP_FK FOREIGN KEY
(
GP_ID
)
REFERENCES GP
(
ID
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Vysledky
ADD CONSTRAINT Vysledky_Jezdci_FK FOREIGN KEY
(
Jezdci_ID
)
REFERENCES Jezdci
(
ID
)
ON
DELETE CASCADE ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             3
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
